version: '3.8'

services:
  neo4j:
    image: neo4j:5-community
    container_name: msp-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    environment:
      # Authentication
      - NEO4J_AUTH=neo4j/msp-password
      
      # Memory configuration
      - NEO4J_server_memory_heap_initial__size=512M
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_server_memory_pagecache__size=512M
      
      # Enable APOC procedures (useful for MSP)
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
      
      # Security
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:7474"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  neo4j_data:
    name: msp_neo4j_data
  neo4j_logs:
    name: msp_neo4j_logs
  neo4j_import:
    name: msp_neo4j_import
  neo4j_plugins:
    name: msp_neo4j_plugins

networks:
  default:
    name: msp_network
